name: 'Override Helm Values'
description: 'Override Helm values with image tags for changed services'

inputs:
  commit-sha:
    description: 'Commit SHA for the image tag'
    required: true
  matrix:
    description: 'Matrix configuration'
    required: true
  changes:
    description: 'Changes output'
    required: true
  helm-values-file:
    description: 'Path to helm-values.yaml file'
    required: false
    default: 'cli/helm-values.yaml'
  github-token:
    description: 'GitHub token for repository access'
    required: true
  saas-config-token:
    description: 'SAAS config read access token'
    required: true
  branch-name:
    description: 'Branch name for deployment'
    required: true
  docker-username:
    description: 'Docker registry username'
    required: true
  docker-password:
    description: 'Docker registry password'
    required: true
  docker-email:
    description: 'Docker registry email'
    required: false
    default: 'dmtkov@flamingo.cx'
  github-actor:
    description: 'GitHub actor username'
    required: true
  ghcr-email:
    description: 'GHCR registry email'
    required: false
    default: 'CI@flamingo.cx'

runs:
  using: 'composite'
  steps:
    - name: Override Helm values
      shell: bash
      env:
        COMMIT_SHA: "${{ inputs.commit-sha }}"
        MATRIX: '${{ inputs.matrix }}'
        CHANGES: '${{ inputs.changes }}'
        HELM_VALUES_FILE: '${{ inputs.helm-values-file }}'
      run: |
        set -euo pipefail
        
        # Validate required inputs
        [ -n "$COMMIT_SHA" ] || { echo "Error: COMMIT_SHA is required" >&2; exit 1; }
        [ -n "$MATRIX" ] || { echo "Error: MATRIX is required" >&2; exit 1; }
        [ -n "$CHANGES" ] || { echo "Error: CHANGES is required" >&2; exit 1; }
        [ -n "$HELM_VALUES_FILE" ] || { echo "Error: HELM_VALUES_FILE is required" >&2; exit 1; }

        mkdir -p "$(dirname "$HELM_VALUES_FILE")" && touch "$HELM_VALUES_FILE"

        # Install yq if needed
        if ! command -v yq &> /dev/null; then
          wget -q https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
        fi
        
        # Function to set image tags
        set_image_tag() {
          local path="$1"
          if yq eval ".apps.$path = \"$COMMIT_SHA\"" -i "$HELM_VALUES_FILE" 2>/dev/null; then
            echo "Updated $path with image tag: $COMMIT_SHA"
          else
            echo "Failed to update $path" >&2
          fi
        }

        echo "Updating Helm values with tag: $COMMIT_SHA"
        # Process each changed service
        jq -c '.[]' <<< "$MATRIX" | while read -r item; do
          name=$(jq -r '.name' <<< "$item")
          changed=$(jq -r --arg name "$name" '.[$name]' <<< "$CHANGES")

          [ "$changed" = "true" ] || continue
          
          # Add image tag to the app's helm values
          case "$name" in
            tactical-*)
              component="${name#tactical-}"
              set_image_tag "tactical-rmm.values.tactical.$component.image.tag"
              ;;
            authentik-postgresql)
              set_image_tag "authentik.values.postgres.image.tag"
              ;;
            fleetmdm | meshcentral)
              set_image_tag "$name.values.server.image.tag"
              ;;
            *)
              set_image_tag "$name.values.image.tag"
              ;;
          esac

        done

    - name: Override repository passwords and branch
      shell: bash
      env:
        HELM_VALUES_FILE: '${{ inputs.helm-values-file }}'
        GITHUB_TOKEN: '${{ inputs.github-token }}'
        SAAS_CONFIG_TOKEN: '${{ inputs.saas-config-token }}'
        BRANCH_NAME: '${{ inputs.branch-name }}'
      run: |
        set -euo pipefail
        yq eval ".deployment.oss.repository.branch = \"$BRANCH_NAME\"" -i "$HELM_VALUES_FILE"
        yq eval ".deployment.saas.repository.password = \"$SAAS_CONFIG_TOKEN\"" -i "$HELM_VALUES_FILE"
        echo "Updated deployment.oss.repository.branch to: $BRANCH_NAME"

    - name: Override registry
      shell: bash
      env:
        HELM_VALUES_FILE: '${{ inputs.helm-values-file }}'
        DOCKER_USERNAME: '${{ inputs.docker-username }}'
        DOCKER_PASSWORD: '${{ inputs.docker-password }}'
        DOCKER_EMAIL: '${{ inputs.docker-email }}'
        GITHUB_ACTOR: '${{ inputs.github-actor }}'
        GITHUB_TOKEN: '${{ inputs.github-token }}'
        GHCR_EMAIL: '${{ inputs.ghcr-email }}'
      run: |
        set -euo pipefail

        # Override Docker registry
        yq eval ".registry.docker.server = \"https://index.docker.io/v1/\"" -i "$HELM_VALUES_FILE"
        yq eval ".registry.docker.username = \"$DOCKER_USERNAME\"" -i "$HELM_VALUES_FILE"
        yq eval ".registry.docker.password = \"$DOCKER_PASSWORD\"" -i "$HELM_VALUES_FILE"
        yq eval ".registry.docker.email = \"$DOCKER_EMAIL\"" -i "$HELM_VALUES_FILE"
        echo "Updated registry.docker configuration"

        # Override GHCR registry
        yq eval ".registry.ghcr.server = \"ghcr.io\"" -i "$HELM_VALUES_FILE"
        yq eval ".registry.ghcr.username = \"$GITHUB_ACTOR\"" -i "$HELM_VALUES_FILE"
        yq eval ".registry.ghcr.password = \"$GITHUB_TOKEN\"" -i "$HELM_VALUES_FILE"
        yq eval ".registry.ghcr.email = \"$GHCR_EMAIL\"" -i "$HELM_VALUES_FILE"
        echo "Updated registry.ghcr configuration"

        cat "$HELM_VALUES_FILE"
